# Use root/example as user/password credentials
version: "3.1"

services:
  #MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: testUserName
      MONGO_INITDB_ROOT_PASSWORD: testUserPassword
      AUTH: admin
    ports:
      - 27017:27017
    volumes:
      - "my_mongodb_data:/data/db"

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: testUserName
      ME_CONFIG_MONGODB_ADMINPASSWORD: testUserPassword
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb

volumes:
  my_mongodb_data:
    driver: local
